sudo: false

language: cpp

compiler: gcc

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libarpack2-dev

env:
  - SUPERLU=ON BLAS=SYSTEM CHOLMOD=ON UMFPACK=ON

before_install:
  # OSX
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install homebrew/science/arpack homebrew/science/superlu ; fi

before_script:
  # linux needs SuperLU from source (APT libsuperlu-dev is still 4.3)
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$SUPERLU" = "ON" ]; then ./install-superlu.sh ; fi
  - if [ "$CHOLMOD" = "ON" -o "$UMFPACK" = "ON" ]; then ./install-suitesparse.sh ; fi
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DSUPERLU=$SUPERLU -DUMFPACK=$UMFPACK -DCHOLMOD=$CHOLMOD ..

script:
  - make install
  - make examples -j2
